// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Skyunion
{
    internal class AudioGroupInfoDefine
    {
        /// <summary> 
        /// 声音事件组ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 组名称
        /// </summary>
        public string name = string.Empty ;

        /// <summary> 
        /// 音量
        /// </summary>
        public float baseVolume = 0 ;

        /// <summary> 
        /// 同时播放数
        /// </summary>
        public int maxCount = 0 ;

        /// <summary> 
        /// 同时播放上限处理
        /// </summary>
        public int maxCountAction = 0 ;

        /// <summary> 
        /// 是否为背景音乐
        /// </summary>
        public int bgm = 0;

        /// <summary> 
        /// 修改的音量组
        /// </summary>
        public List<int> modifyGroup = null;

        /// <summary> 
        /// 修正的音量
        /// </summary>
        public List<float> modifyVolume = null;
    }
}