// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Skyunion
{
    internal class AudioInfoDefine
    {
        /// <summary> 
        /// 声音事件ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 声音事件名称
        /// </summary>
        public string name = string.Empty;

        /// <summary> 
        /// 分组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 播放模式
        /// </summary>
        public int mode = 0 ;

        /// <summary> 
        /// 同时播放数
        /// </summary>
        public int maxCount = 0 ;

        /// <summary> 
        /// 同时播放上限处理
        /// </summary>
        public int maxCountAction = 0 ;

        /// <summary> 
        /// 间隔时间
        /// </summary>
        public List<float> interval = null ;

        /// <summary> 
        /// 音量
        /// </summary>
        public float volume = 0 ;

        /// <summary> 
        /// 淡出时间
        /// </summary>
        public float fadeTime = 0 ;

        /// <summary> 
        /// 3D音效
        /// </summary>
        public int config3D = 0 ;

        /// <summary> 
        /// 音效文件
        /// </summary>
        public List<string> audios = null ;

    }
}