//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Msg.proto
namespace Msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_Register_C2S")]
  public partial class Msg_Register_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_Register_C2S() {}
    
    private byte[] _szName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"szName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] szName
    {
      get { return _szName; }
      set { _szName = value; }
    }
    private byte[] _szPassword;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"szPassword", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] szPassword
    {
      get { return _szPassword; }
      set { _szPassword = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_Register_S2C")]
  public partial class Msg_Register_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_Register_S2C() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_Login_C2S")]
  public partial class Msg_Login_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_Login_C2S() {}
    
    private byte[] _szName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"szName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] szName
    {
      get { return _szName; }
      set { _szName = value; }
    }
    private byte[] _szPassword;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"szPassword", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] szPassword
    {
      get { return _szPassword; }
      set { _szPassword = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_Login_S2C")]
  public partial class Msg_Login_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_Login_S2C() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CreateRoom_C2S")]
  public partial class Msg_CreateRoom_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_CreateRoom_C2S() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CreateRoom_S2C")]
  public partial class Msg_CreateRoom_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_CreateRoom_S2C() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_EnterRoom_C2S")]
  public partial class Msg_EnterRoom_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_EnterRoom_C2S() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_EnterRoom_S2C")]
  public partial class Msg_EnterRoom_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_EnterRoom_S2C() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _number = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int number
    {
      get { return _number; }
      set { _number = value; }
    }
    private byte[] _szName = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"szName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] szName
    {
      get { return _szName; }
      set { _szName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_ChangeState_C2S")]
  public partial class Msg_ChangeState_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_ChangeState_C2S() {}
    
    private int _number1 = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"number1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int number1
    {
      get { return _number1; }
      set { _number1 = value; }
    }
    private int _number2 = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"number2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int number2
    {
      get { return _number2; }
      set { _number2 = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _ready = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ready", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ready
    {
      get { return _ready; }
      set { _ready = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_ChangeState_S2C")]
  public partial class Msg_ChangeState_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_ChangeState_S2C() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _number1 = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"number1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int number1
    {
      get { return _number1; }
      set { _number1 = value; }
    }
    private int _number2 = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"number2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int number2
    {
      get { return _number2; }
      set { _number2 = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _ready = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ready", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ready
    {
      get { return _ready; }
      set { _ready = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_Expel_C2S")]
  public partial class Msg_Expel_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_Expel_C2S() {}
    
    private int _number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int number
    {
      get { return _number; }
      set { _number = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _userid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_Expel_S2C")]
  public partial class Msg_Expel_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_Expel_S2C() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _number = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int number
    {
      get { return _number; }
      set { _number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_StartGame_C2S")]
  public partial class Msg_StartGame_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_StartGame_C2S() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_StartGame_S2C")]
  public partial class Msg_StartGame_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_StartGame_S2C() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_ExitRoom_C2S")]
  public partial class Msg_ExitRoom_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_ExitRoom_C2S() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int number
    {
      get { return _number; }
      set { _number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_ExitRoom_S2C")]
  public partial class Msg_ExitRoom_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_ExitRoom_S2C() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _number = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int number
    {
      get { return _number; }
      set { _number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_GetRoomMen_C2S")]
  public partial class Msg_GetRoomMen_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_GetRoomMen_C2S() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_GetRoomMen_S2C")]
  public partial class Msg_GetRoomMen_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_GetRoomMen_S2C() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _number = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> number
    {
      get { return _number; }
    }
  
    private readonly global::System.Collections.Generic.List<byte[]> _szName = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(3, Name=@"szName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> szName
    {
      get { return _szName; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _tankType = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"tankType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> tankType
    {
      get { return _tankType; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _ready = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"ready", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> ready
    {
      get { return _ready; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_FANGJIANLT_C2S")]
  public partial class Msg_FANGJIANLT_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_FANGJIANLT_C2S() {}
    
    private byte[] _szContent;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"szContent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] szContent
    {
      get { return _szContent; }
      set { _szContent = value; }
    }
    private byte[] _szName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"szName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] szName
    {
      get { return _szName; }
      set { _szName = value; }
    }
    private int _houseid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"houseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int houseid
    {
      get { return _houseid; }
      set { _houseid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_FANGJIANLT_S2C")]
  public partial class Msg_FANGJIANLT_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_FANGJIANLT_S2C() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private byte[] _szContent = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"szContent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] szContent
    {
      get { return _szContent; }
      set { _szContent = value; }
    }
    private byte[] _szName = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"szName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] szName
    {
      get { return _szName; }
      set { _szName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_VEC_C2S")]
  public partial class Msg_VEC_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_VEC_C2S() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _direction;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private int _ingrass;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ingrass", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ingrass
    {
      get { return _ingrass; }
      set { _ingrass = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_VEC_S2C")]
  public partial class Msg_VEC_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_VEC_S2C() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _direction;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _hide;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"hide", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hide
    {
      get { return _hide; }
      set { _hide = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_PICKSIDE_C2S")]
  public partial class Msg_PICKSIDE_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_PICKSIDE_C2S() {}
    
    private int _side;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"side", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int side
    {
      get { return _side; }
      set { _side = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_PICKSIDE_S2C")]
  public partial class Msg_PICKSIDE_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_PICKSIDE_S2C() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_AMMO_C2S")]
  public partial class Msg_AMMO_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_AMMO_C2S() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _direction;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _id_shooter;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"id_shooter", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id_shooter
    {
      get { return _id_shooter; }
      set { _id_shooter = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_AMMO_S2C")]
  public partial class Msg_AMMO_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_AMMO_S2C() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _direction;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_DAMAGE_C2S")]
  public partial class Msg_DAMAGE_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_DAMAGE_C2S() {}
    
    private int _damage;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private int _id_hurt;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id_hurt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id_hurt
    {
      get { return _id_hurt; }
      set { _id_hurt = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_DAMAGE_S2C")]
  public partial class Msg_DAMAGE_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_DAMAGE_S2C() {}
    
    private int _damage;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_GETITEM_S2C")]
  public partial class Msg_GETITEM_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_GETITEM_S2C() {}
    
    private int _kind;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"kind", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int kind
    {
      get { return _kind; }
      set { _kind = value; }
    }
    private int _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_DEATH_S2C")]
  public partial class Msg_DEATH_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_DEATH_S2C() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_POINTTAKING_S2C")]
  public partial class Msg_POINTTAKING_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_POINTTAKING_S2C() {}
    
    private int _team;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int team
    {
      get { return _team; }
      set { _team = value; }
    }
    private int _percent;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"percent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int percent
    {
      get { return _percent; }
      set { _percent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_POINTTAKEN_S2C")]
  public partial class Msg_POINTTAKEN_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_POINTTAKEN_S2C() {}
    
    private int _team;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int team
    {
      get { return _team; }
      set { _team = value; }
    }
    private int _pointnumber;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pointnumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pointnumber
    {
      get { return _pointnumber; }
      set { _pointnumber = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_ADDSCORES_S2C")]
  public partial class Msg_ADDSCORES_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_ADDSCORES_S2C() {}
    
    private int _socres;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"socres", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int socres
    {
      get { return _socres; }
      set { _socres = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_ENDGAME_S2C")]
  public partial class Msg_ENDGAME_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_ENDGAME_S2C() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _team;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int team
    {
      get { return _team; }
      set { _team = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_POINTDESPUTE_S2C")]
  public partial class Msg_POINTDESPUTE_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_POINTDESPUTE_S2C() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_ROOMINFO_S2C")]
  public partial class Msg_ROOMINFO_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_ROOMINFO_S2C() {}
    
    private int _masterid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"masterid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int masterid
    {
      get { return _masterid; }
      set { _masterid = value; }
    }
    private byte[] _masterusername;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"masterusername", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] masterusername
    {
      get { return _masterusername; }
      set { _masterusername = value; }
    }
    private int _roomid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomid
    {
      get { return _roomid; }
      set { _roomid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_ROOMLIST_S2C")]
  public partial class Msg_ROOMLIST_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_ROOMLIST_S2C() {}
    
    private readonly global::System.Collections.Generic.List<Msg_ROOMINFO_S2C> _room = new global::System.Collections.Generic.List<Msg_ROOMINFO_S2C>();
    [global::ProtoBuf.ProtoMember(1, Name=@"room", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Msg_ROOMINFO_S2C> room
    {
      get { return _room; }
    }
  
    private int _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_ROOMINFOREQUEST_C2S")]
  public partial class Msg_ROOMINFOREQUEST_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_ROOMINFOREQUEST_C2S() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_USERINFO_S2C")]
  public partial class Msg_USERINFO_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_USERINFO_S2C() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private byte[] _username;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] username
    {
      get { return _username; }
      set { _username = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _team;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int team
    {
      get { return _team; }
      set { _team = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_USERINFOLISTOS_S2C")]
  public partial class MSG_USERINFOLISTOS_S2C : global::ProtoBuf.IExtensible
  {
    public MSG_USERINFOLISTOS_S2C() {}
    
    private readonly global::System.Collections.Generic.List<Msg_USERINFO_S2C> _userinfo = new global::System.Collections.Generic.List<Msg_USERINFO_S2C>();
    [global::ProtoBuf.ProtoMember(1, Name=@"userinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Msg_USERINFO_S2C> userinfo
    {
      get { return _userinfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_VECOS_S2C")]
  public partial class MSG_VECOS_S2C : global::ProtoBuf.IExtensible
  {
    public MSG_VECOS_S2C() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _direction;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private int _ingrass;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ingrass", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ingrass
    {
      get { return _ingrass; }
      set { _ingrass = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_VECOSLIST_S2C")]
  public partial class MSG_VECOSLIST_S2C : global::ProtoBuf.IExtensible
  {
    public MSG_VECOSLIST_S2C() {}
    
    private readonly global::System.Collections.Generic.List<MSG_VECOS_S2C> _vec = new global::System.Collections.Generic.List<MSG_VECOS_S2C>();
    [global::ProtoBuf.ProtoMember(1, Name=@"vec", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MSG_VECOS_S2C> vec
    {
      get { return _vec; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_INFOAC_C2S")]
  public partial class MSG_INFOAC_C2S : global::ProtoBuf.IExtensible
  {
    public MSG_INFOAC_C2S() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgType")]
    public enum MsgType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"REGISTER_C2S", Value=1010)]
      REGISTER_C2S = 1010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REGISTER_S2C", Value=2010)]
      REGISTER_S2C = 2010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_C2S", Value=1020)]
      LOGIN_C2S = 1020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_S2C", Value=2020)]
      LOGIN_S2C = 2020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_ROOM_C2S", Value=1030)]
      CREATE_ROOM_C2S = 1030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_ROOM_S2C", Value=2030)]
      CREATE_ROOM_S2C = 2030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTER_ROOM_C2S", Value=1040)]
      ENTER_ROOM_C2S = 1040,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTER_ROOM_S2C", Value=2040)]
      ENTER_ROOM_S2C = 2040,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHANGE_STATE_C2S", Value=1050)]
      CHANGE_STATE_C2S = 1050,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHANGE_STATE_S2C", Value=2050)]
      CHANGE_STATE_S2C = 2050,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXPEL_C2S", Value=1060)]
      EXPEL_C2S = 1060,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXPEL_S2C", Value=2060)]
      EXPEL_S2C = 2060,
            
      [global::ProtoBuf.ProtoEnum(Name=@"START_GAME_C2S", Value=1070)]
      START_GAME_C2S = 1070,
            
      [global::ProtoBuf.ProtoEnum(Name=@"START_GAME_S2C", Value=2070)]
      START_GAME_S2C = 2070,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXIT_ROOM_C2S", Value=1080)]
      EXIT_ROOM_C2S = 1080,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXIT_ROOM_S2C", Value=2080)]
      EXIT_ROOM_S2C = 2080,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_ROOMMEN_C2S", Value=1090)]
      GET_ROOMMEN_C2S = 1090,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_ROOMMEN_S2C", Value=2090)]
      GET_ROOMMEN_S2C = 2090,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FANGJIANLT_C2S", Value=1110)]
      FANGJIANLT_C2S = 1110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FANGJIANLT_S2C", Value=2110)]
      FANGJIANLT_S2C = 2110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VEC_C2S", Value=1120)]
      VEC_C2S = 1120,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VEC_S2C", Value=2120)]
      VEC_S2C = 2120,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PickSide_C2S", Value=1130)]
      PickSide_C2S = 1130,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PickSide_S2C", Value=2130)]
      PickSide_S2C = 2130,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ammo_C2S", Value=1140)]
      Ammo_C2S = 1140,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ammo_S2C", Value=2131)]
      Ammo_S2C = 2131,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Damage_C2S", Value=2132)]
      Damage_C2S = 2132,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Damage_S2C", Value=2140)]
      Damage_S2C = 2140,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetItem_S2C", Value=2150)]
      GetItem_S2C = 2150,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Death_S2C", Value=2160)]
      Death_S2C = 2160,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PointTaking", Value=2170)]
      PointTaking = 2170,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PointTaken", Value=2180)]
      PointTaken = 2180,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddSocres", Value=2190)]
      AddSocres = 2190,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EndGame", Value=2191)]
      EndGame = 2191,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PointDispute", Value=2192)]
      PointDispute = 2192,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomInfo", Value=2193)]
      RoomInfo = 2193,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomList", Value=2194)]
      RoomList = 2194,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomInfoRequest", Value=1170)]
      RoomInfoRequest = 1170,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UserInfo", Value=2195)]
      UserInfo = 2195,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UserInfoOS", Value=2196)]
      UserInfoOS = 2196,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VECOS", Value=2197)]
      VECOS = 2197,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VecOsList", Value=2198)]
      VecOsList = 2198,
            
      [global::ProtoBuf.ProtoEnum(Name=@"InfoAc", Value=2199)]
      InfoAc = 2199
    }
  
}